### ISSUE TITLE
Question about scrolling filtered video

### ISSUE THREAD

**Issue by Knights22** [NghiaTranUIT/FeSlideFilter#2]
If i use GPUImage to pre-process the video files and add to an array, then i can use the scrollview to slide through different video filters?

**Comment by NghiaTranUIT** [comment]
Currently. FeSlideFilter doesn't support on video. But of you need this
feature. I recommend SCRecorder https://github.com/rFlex/SCRecorder

It has helper class to do it. Please look at example of this library :)

On Tuesday, March 24, 2015, Knights22 notifications@github.com wrote:

> If i use GPUImage to pre-process the video files and add to an array, then
> i can use the scrollview to slide through different video filters?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NghiaTranUIT/FeSlideFilter/issues/2.

## 

P : +84 1269945200

W : www.nghiatran.me

M : vinhnghiatran@gmail.com

**Comment by Knights22** [comment]
Thank You, also thank you for the wonderful blog posts!
