### ISSUE TITLE
How can I swipe the other direction?

### ISSUE THREAD

**Issue by instaqwe** [NghiaTranUIT/FeSlideFilter#3]
Awesome control, but I want to swipe right instead of left, is there any way I can do that? 
I really appriciate any help. 

(Context: I used CGAffineTransformMakeScale(-1, 1) to flip the image and now it's swiping in the other direction)

**Comment by NghiaTranUIT** [comment]
Sorry you.

Currently, FeSlideFilter doesn't support swipe from right to left as you expect.

But i will implement it for you late :)

Thanks for using
