### ISSUE TITLE
When passing a UIImage value from camera, pic is sideways?

### ISSUE THREAD

**Issue by Knights22** [NghiaTranUIT/FeSlideFilter#4]
When pass a UIImage value from camera, why is the pic is always sideways? Its not the camera because if i just use a uiimageview the orientation is correct. Could this be the reason http://stackoverflow.com/questions/20657131/uiimage-sideway-after-converting-it-from-ciimage

**Comment by NghiaTranUIT** [comment]
Thanks for using my open-source.

If my memory is good, i remember the default orientation of photo which captured by Camera is 6 - Rotated 90' CCW.

So it's reason why pic is always sideways, UIImageView rotate it automatically.

Solution : Google has bunch of answer to "fix orientation uiimage", and your link is one of them.

Thanks :)

**Comment by Knights22** [comment]
Thank you!
